/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#ifndef PLUGINPROCESSOR_H_INCLUDED
#define PLUGINPROCESSOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "MONSTR.h"
#include "ParameterData.h"


//==============================================================================
/**
*/
class MonstrAudioProcessor  : public AudioProcessor
{
public:
    //==============================================================================
    MonstrAudioProcessor();
    ~MonstrAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer&, MidiBuffer&) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================
    const String getName() const override;

    int getNumParameters() override;
    float getParameter (int index) override;
    void setParameter (int index, float newValue) override;
    bool isParameterAutomatable(int parameterIndex) const override;

    const String getParameterName (int index) override;
    const String getParameterText (int index) override;

    const String getInputChannelName (int channelIndex) const override;
    const String getOutputChannelName (int channelIndex) const override;
    bool isInputChannelStereoPair (int index) const override;
    bool isOutputChannelStereoPair (int index) const override;

    bool acceptsMidi() const override;
    bool producesMidi() const override;
    bool silenceInProducesSilenceOut() const override;
    double getTailLengthSeconds() const override;

    //==============================================================================
    int getNumPrograms() override;
    int getCurrentProgram() override;
    void setCurrentProgram (int index) override;
    const String getProgramName (int index) override;
    void changeProgramName (int index, const String& newName) override;

    //==============================================================================
    void getStateInformation (MemoryBlock& destData) override;
    void setStateInformation (const void* data, int sizeInBytes) override;
    
    enum Parameters {
        isBypassedBand1 = 0,
        widthBand1,
        
        crossoverLower,
        
        isBypassedBand2,
        widthBand2,
        
        crossoverUpper,
        
        isBypassedBand3,
        widthBand3,
        
        totalNumParams
    };
    
    bool NeedsUIUpdate() {
        return UIUpdateFlag;
    }
    
    void RequestUIUpdate() {
        UIUpdateFlag = true;
    }
    
    void ClearUIUpdate() {
        UIUpdateFlag = false;
    }

private:
    MONSTR mMONSTR;
    bool UIUpdateFlag;
    
    String floatVectorToString(const std::vector<float>& fData) const;
    
    int stringToFloatVector(const String sFloatCSV, std::vector<float>& fData, int maxNumFloat) const;
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MonstrAudioProcessor)
};


#endif  // PLUGINPROCESSOR_H_INCLUDED
