name: CI Main

on: [push, pull_request]

jobs:
  BuildWindows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: SetupMSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: RunBuild
        shell: cmd
        run: Scripts\BuildWindows.bat
      - uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: monstr-windows
          path: Builds/VisualStudio2019/Win32/Debug/VST3/*.vst3
